### ISSUE TITLE
caribu infinitisation

### ISSUE THREAD

**Issue by chrlecarpentier** [openalea-incubator/WALTer#11]
Use caribu with infinitize pattern

**Comment by chrlecarpentier** [comment]
Infinitization is integrated in one branch, this takes very long time (1 minutes instead of 0.5 sec for one step)

**Comment by christian34** [comment]
The bug has been fixed and ready to merge in PR #17

**Comment by Emblanc** [comment]
Great !
I will test the duration of simulations on my computer before I merge PR #17

**Comment by Emblanc** [comment]
Simulations with infinitization seem to work great now ! I merged PR #17.
