### ISSUE TITLE
Input / Output simulation management 

### ISSUE THREAD

**Issue by christian34** [openalea-incubator/WALTer#3]
Currently, outputs are accumulating in package dir : should be in a user defined dir or tmp dir for tests

**Comment by pradal** [comment]
**Strategies**:

- One Project per simulation 
    - Create a new dir for each simulation, with inputs and outputs
    -  Define a name: walter_$time_$date
    - copy walter.lpy, inputs, outputs

    - Pro: 
        - Each simulation is independant
     - Cons:
         - Lots of different dirs
         - Need to manage, remove, retrieve results for analysis

- One Project per group of simulation 
    - Same of previous but put all the simulation in the same dir
    - Pro: 
        - Ease the management of a group of simulation
     - Cons:
         - difference between a group of simulation and one simulation

 **Solution**
- Create a new directory (cwd: '.')
- Lanch a command walter with input parameters (eg sim_scheme.csv)
    - walter -i sim_scheme.csv
- Copy all the inputs, generate output, and also logs, profiling, errors, ...
