### ISSUE TITLE
Curved leaves

### ISSUE THREAD

**Issue by Emblanc** [openalea-incubator/WALTer#35]
Adding a curvature of the leaves to improve realism

**Comment by Jeroome** [comment]
Question on this enhancement:
- Is it having a big cost on calculation time, as curved surfaces certainly generate more triangles for Caribu?

**Comment by pradal** [comment]
It depends on how the leaves are represented today.
However, we have developped mesh simplification algorithms for leaves and studied the best compromise between accuracy and computation time:

Fournier, Pradal, 2012
https://doi.org/10.1109/PMA.2012.6524823

**Comment by Emblanc** [comment]
With the curved leaves, modifications will have to be made to the calculation of the GAI

**Comment by Emblanc** [comment]
In the walter_leaf_mesh function, the argument "compensate" allows to compensate for area error.
There are significant differences between the results of a simulation done with compensate = False and the same simulation done with compensate = True.
![GAI_compensate](https://user-images.githubusercontent.com/34065523/56292138-e5966100-6126-11e9-8764-43dd046ca55d.jpeg)
![Tillering_dyn_compensate](https://user-images.githubusercontent.com/34065523/56292139-e62ef780-6126-11e9-9944-0a5c136b9c68.jpeg)
![Int_light_compensate](https://user-images.githubusercontent.com/34065523/56292141-e62ef780-6126-11e9-97db-c9490f9a9b05.jpeg)

**Comment by Emblanc** [comment]
[output_blade_scale_radius.csv.zip](https://github.com/openalea-incubator/WALTer/files/3090579/output_blade_scale_radius.csv.zip)

**Comment by Emblanc** [comment]
Here are the same graphs as previously but all with the same x-axis (in days) and from simulations that were made after the fix of issue #82 on negative surfaces.

![GAI_Compensate](https://user-images.githubusercontent.com/34065523/56366051-81d96a00-61f2-11e9-8463-ddff6ee5b440.jpeg)

![Tillering_dyn_Compensate](https://user-images.githubusercontent.com/34065523/56366057-856cf100-61f2-11e9-856b-c95075b274e0.jpeg)

![Int_light_Compensate](https://user-images.githubusercontent.com/34065523/56366062-89007800-61f2-11e9-8169-c5abe7aad7db.jpeg)
