### ISSUE TITLE
Change test reference automatically

### ISSUE THREAD

**Issue by pradal** [openalea-incubator/WALTer#57]
Run all the tests to recreate all the files that are used to validate the tests.

**Comment by pradal** [comment]
@bilalderouich

**Comment by christian34** [comment]
done in global test branch now (change_ref.py) https://github.com/openalea-incubator/WALTer/pull/44/commits/1c5436740bd3f98e9da0f6bf6bc7e3ebe5966a9f

**Comment by Emblanc** [comment]
This issue was closed by the PR #44
