### ISSUE TITLE
Problem installing WALTer on Ubuntu 16

### ISSUE THREAD

**Issue by Emblanc** [openalea-incubator/WALTer#58]
I tried to install WALTer on a computer with Ubuntu 16 following the instructions on the wiki, but when I run the command nosetests in the test directory (and in my walter environment), I get an error : 
> ImportError: No module named lpy

If I try to open lpy in my environment, I get :
> RuntimeError: the sip module implements API v11.0 but the PyQGLViewerQt4 module requires API v11.3

After updating sip, I can open lpy normally (still in my walter environment)  but I still get the same error when I try to run nosetests

**Comment by pradal** [comment]
Do you have the problem yet?

**Comment by Emblanc** [comment]
I tried again today and the problem is still here

**Comment by pradal** [comment]
Hi Emmanuelle,
Can you report the error in detail?
You have to open a new shell, activate the environment and report the error?

One usefull info will be given by the command:
conda info --all

**Comment by Emblanc** [comment]
Hi Christophe,
Here is what happens when I run nosetests :

> (walter) walter@stagedeap2:~/WALTer/test$ nosetests
EEEEE
======================================================================
ERROR: Failure: ImportError (No module named lpy)
----------------------------------------------------------------------
>Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/walter/WALTer/test/test_command_line.py", line 3, in <module>
    from walter.command_line import walter_parser
  File "/home/walter/WALTer/src/walter/command_line.py", line 9, in <module>
    from walter import project
  File "/home/walter/WALTer/src/walter/project.py", line 17, in <module>
    from openalea.lpy import Lsystem
ImportError: No module named lpy

>======================================================================
ERROR: Failure: ImportError (No module named lpy)
----------------------------------------------------------------------
>Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/walter/WALTer/test/test_cut_module.py", line 4, in <module>
    from openalea.lpy import Lsystem
ImportError: No module named lpy

>======================================================================
ERROR: Failure: ImportError (No module named lpy)
----------------------------------------------------------------------
>Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/walter/WALTer/test/test_light_interception.py", line 1, in <module>
    from walter import project
  File "/home/walter/WALTer/src/walter/project.py", line 17, in <module>
    from openalea.lpy import Lsystem
ImportError: No module named lpy

>======================================================================
ERROR: Failure: ImportError (No module named lpy)
----------------------------------------------------------------------
>Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/walter/WALTer/test/test_project.py", line 1, in <module>
    from walter import project
  File "/home/walter/WALTer/src/walter/project.py", line 17, in <module>
    from openalea.lpy import Lsystem
ImportError: No module named lpy

>======================================================================
>ERROR: Failure: ImportError (No module named lpy)
----------------------------------------------------------------------
>Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/walter/WALTer/test/test_run_project.py", line 1, in <module>
    from walter import project
  File "/home/walter/WALTer/src/walter/project.py", line 17, in <module>
    from openalea.lpy import Lsystem
ImportError: No module named lpy

----------------------------------------------------------------------
>Ran 5 tests in 0.001s

>FAILED (errors=5)

**Comment by pradal** [comment]
Thanks. It may be related to 2 things: either you use a develop mode for Walter (pure namespace are broken) or a problem of import (binary compatibility).

Can you create a new environment like:

conda create -n lpy -c openalea openalea.lpy boost==1.66
conda activate lpy (or source activate lpy)
lpy

If it works, I suppose that the pure namespace is broken.

**Comment by Emblanc** [comment]
And here is the result from conda info --all :

> (walter) walter@stagedeap2:~/WALTer/test$ conda info --all

     active environment : walter
    active env location : /home/walter/miniconda2/envs/walter
            shell level : 1
       user config file : /home/walter/.condarc
      populated config files : 
          conda version : 4.5.1
    conda-build version : not installed
         python version : 2.7.14.final.0
       base environment : /home/walter/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/walter/miniconda2/pkgs
                          /home/walter/.conda/pkgs
       envs directories : /home/walter/miniconda2/envs
                          /home/walter/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.1 requests/2.18.4 CPython/2.7.14 Linux/4.4.0-137-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1002:1002
             netrc file : None
           offline mode : False

># conda environments:
#
>base                     /home/walter/miniconda2
walter                *  /home/walter/miniconda2/envs/walter

>sys.version: 2.7.14 |Anaconda, Inc.| (default, Mar 27...
sys.prefix: /home/walter/miniconda2
sys.executable: /home/walter/miniconda2/bin/python
conda location: /home/walter/miniconda2/lib/python2.7/site-packages/conda
conda-build: None
conda-env: /home/walter/miniconda2/bin/conda-env
user site dirs: 

>CIO_TEST: <not set>
CONDA_DEFAULT_ENV: walter
CONDA_EXE: /home/walter/miniconda2/bin/conda
CONDA_PREFIX: /home/walter/miniconda2/envs/walter
CONDA_PROMPT_MODIFIER: (walter) 
CONDA_PYTHON_EXE: /home/walter/miniconda2/bin/python
CONDA_ROOT: /home/walter/miniconda2
CONDA_SHLVL: 1
LD_LIBRARY_PATH: /usr/lib/python2.7/dist-packages/lib:/usr/lib/python2.7/dist-packages/lib:/usr/lib/python2.7/dist-packages/lib:/usr/lib/python2.7/dist-packages/lib:/usr/lib/python2.7/dist-packages/lib:/usr/lib/python2.7/dist-packages/lib:/usr/lib/python2.7/dist-packages/lib:/usr/lib/python2.7/dist-packages/lib:/usr/lib/python2.7/dist-packages/lib:/usr/lib/python2.7/dist-packages/lib:/usr/lib/python2.7/dist-packages/lib:/usr/lib/python2.7/dist-packages/lib:/usr/local/lib
PATH: /home/walter/miniconda2/envs/walter/bin:/home/walter/miniconda2/bin:/usr/lib/python2.7/dist-packages/bin:/usr/local/lib/python2.7/dist-packages/alinea.caribu-7.0.0-py2.7-linux-x86_64.egg/bin:/usr/lib/python2.7/dist-packages/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>


>WARNING: could not import _license.show_info
># try:
># $ conda install -n root _license

**Comment by pradal** [comment]
You have a problem due to the fact that LD_LIBRARY_PATH is defined.

Can you test in your shell:
export LD_LIBRARY_PATH=
And retry

**Comment by Emblanc** [comment]
Ok, should I be in my walter environement to run " export LD_LIBRARY_PATH=" ?

**Comment by pradal** [comment]
No just in your shell. We will sse later how to modify your env.

**Comment by Emblanc** [comment]
Ok, I ran  " export LD_LIBRARY_PATH=" .
Here is the new result from conda info --all :

> walter@stagedeap2:~/WALTer/test$ conda info --all

     active environment : None
            shell level : 0
       user config file : /home/walter/.condarc
    populated config files : 
          conda version : 4.5.1
    conda-build version : not installed
         python version : 2.7.14.final.0
       base environment : /home/walter/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/walter/miniconda2/pkgs
                          /home/walter/.conda/pkgs
       envs directories : /home/walter/miniconda2/envs
                          /home/walter/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.1 requests/2.18.4 CPython/2.7.14 Linux/4.4.0-137-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1002:1002
             netrc file : None
           offline mode : False

> #

 conda environments:
#
base                  *  /home/walter/miniconda2
lpy                      /home/walter/miniconda2/envs/lpy
walter                   /home/walter/miniconda2/envs/walter

sys.version: 2.7.14 |Anaconda, Inc.| (default, Mar 27...
sys.prefix: /home/walter/miniconda2
sys.executable: /home/walter/miniconda2/bin/python
conda location: /home/walter/miniconda2/lib/python2.7/site-packages/conda
conda-build: None
conda-env: /home/walter/miniconda2/bin/conda-env
user site dirs: 

CIO_TEST: <not set>
CONDA_ROOT: /home/walter/miniconda2
CONDA_SHLVL: 0
LD_LIBRARY_PATH: 
PATH: /home/walter/miniconda2/bin:/usr/lib/python2.7/dist-packages/bin:/usr/local/lib/python2.7/dist-packages/alinea.caribu-7.0.0-py2.7-linux-x86_64.egg/bin:/usr/lib/python2.7/dist-packages/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>


WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license

**Comment by pradal** [comment]
Excellent. Now, run again nosetests

**Comment by Emblanc** [comment]
The problem remains :

> (walter) walter@stagedeap2:~/WALTer/test$ nosetests
EEEEE
======================================================================
ERROR: Failure: ImportError (No module named lpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/walter/WALTer/test/test_command_line.py", line 3, in <module>
    from walter.command_line import walter_parser
  File "/home/walter/WALTer/src/walter/command_line.py", line 9, in <module>
    from walter import project
  File "/home/walter/WALTer/src/walter/project.py", line 17, in <module>
    from openalea.lpy import Lsystem
ImportError: No module named lpy

======================================================================
ERROR: Failure: ImportError (No module named lpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/walter/WALTer/test/test_cut_module.py", line 4, in <module>
    from openalea.lpy import Lsystem
ImportError: No module named lpy

======================================================================
ERROR: Failure: ImportError (No module named lpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/walter/WALTer/test/test_light_interception.py", line 1, in <module>
    from walter import project
  File "/home/walter/WALTer/src/walter/project.py", line 17, in <module>
    from openalea.lpy import Lsystem
ImportError: No module named lpy

======================================================================
ERROR: Failure: ImportError (No module named lpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/walter/WALTer/test/test_project.py", line 1, in <module>
    from walter import project
  File "/home/walter/WALTer/src/walter/project.py", line 17, in <module>
    from openalea.lpy import Lsystem
ImportError: No module named lpy

======================================================================
ERROR: Failure: ImportError (No module named lpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/walter/WALTer/test/test_run_project.py", line 1, in <module>
    from walter import project
  File "/home/walter/WALTer/src/walter/project.py", line 17, in <module>
    from openalea.lpy import Lsystem
ImportError: No module named lpy

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)

**Comment by pradal** [comment]
Can you just run the command lpy?

**Comment by Emblanc** [comment]
Lpy opens normally in my walter environment.
Here is the result of conda list :

> (walter) walter@stagedeap2:~/WALTer/test$  conda list
# packages in environment at /home/walter/miniconda2/envs/walter:
#
# Name                    Version                   Build  Channel
alinea.astk               2.0.2                         0    openalea
alinea.caribu             7.0.5                    py27_0    openalea
ann                       1.1.2                         0    openalea
backports                 1.0                      py27_1  
backports.os              0.1.1                    py27_0  
backports.shutil_get_terminal_size 1.0.0                    py27_2  
backports_abc             0.5              py27h7b3c97b_0  
blas                      1.0                         mkl  
bleach                    3.0.2                    py27_0  
blosc                     1.15.1               hfc679d8_0    conda-forge
boost                     1.66.0           py27h39e3cac_0    openalea
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.03.07                    0  
cairo                     1.14.8                        0  
certifi                   2018.10.15               py27_0  
cgal                      4.11.0                        0    openalea
configparser              3.5.0            py27h5117587_0  
contextlib2               0.5.5                    py27_0  
cycler                    0.10.0           py27hc7354d3_0  
decorator                 4.3.0                    py27_0  
entrypoints               0.2.3                    py27_2  
enum34                    1.1.6                    py27_1  
ephem                     3.7.6.0          py27h470a237_1    conda-forge
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
funcsigs                  1.0.2                      py_2    conda-forge
functools32               3.2.3.2                  py27_1  
future                    0.17.1                   py27_0  
futures                   3.2.0                    py27_0  
gmp                       6.1.2                h6c8ec71_1  
hdf5                      1.10.1                        2    conda-forge
icu                       54.1                          0  
importlib_metadata        0.6                      py27_0  
intel-openmp              2019.1                      144  
ipaddress                 1.0.22                   py27_0  
ipykernel                 4.10.0                   py27_0  
ipython                   5.8.0                    py27_0  
ipython_genutils          0.2.0                    py27_0  
jinja2                    2.10                     py27_0  
jsonschema                2.6.0            py27h7ed5aa4_0  
jupyter_client            5.2.3                    py27_0  
jupyter_core              4.4.0                    py27_0  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.14                          0  
libpng                    1.6.35               hbc83047_0  
libqglviewer              2.6.4                         1    openalea
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libxml2                   2.9.4                         0  
llvmlite                  0.26.0           py27hd28b015_0    conda-forge
lzo                       2.10                 h470a237_0    conda-forge
markupsafe                1.1.0            py27h7b6447c_0  
matplotlib                1.5.1               np111py27_0  
mistune                   0.8.4            py27h7b6447c_0  
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6            py27h7dd41cf_0  
mkl_random                1.0.1            py27h4414c95_1  
mpfr                      4.0.1                hdf1c602_3  
nbconvert                 5.3.1                    py27_0  
nbformat                  4.4.0                    py27_0  
ncurses                   6.1                  he6710b0_1  
notebook                  5.7.2                    py27_0  
numba                     0.41.0           py27hf8a1672_0    conda-forge
numexpr                   2.6.8            py27hf8a1672_0    conda-forge
numpy                     1.11.3           py27h3dfced4_4  
numpy-base                1.15.4           py27h81de0dd_0  
openalea.core             2.0.1                    py27_1    openalea
openalea.deploy           2.1.6                    py27_0    openalea
openalea.lpy              2.7.1                         2    openalea
openalea.mtg              2.0.1                    py27_1    openalea
openalea.plantgl          2.23.2           py27he6552ab_1    openalea
openalea.vpltk            2.0.2                    py27_0    openalea
openssl                   1.1.1a               h7b6447c_0  
pandas                    0.23.4           py27h04863e7_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py27_1  
path.py                   11.5.0                   py27_0  
pathlib2                  2.3.2                    py27_0  
pexpect                   4.6.0                    py27_0  
pickleshare               0.7.5                    py27_0  
pip                       18.1                     py27_0  
pixman                    0.34.0               hceecf20_3  
prometheus_client         0.4.2                    py27_0  
prompt_toolkit            1.0.15           py27h1b593e1_0  
ptyprocess                0.6.0                    py27_0  
pvlib-python              0.6.0                      py_0    conda-forge
pycairo                   1.13.3           py27hea6d626_0  
pygments                  2.2.0            py27h4a8b6f5_0  
pyopengl                  3.1.1a1                  py27_0  
pyparsing                 2.3.0                    py27_0  
pyqglviewer               1.0.0                    py27_1    openalea
pyqt                      4.11.4                   py27_4  
pytables                  3.4.4                    py27_8    conda-forge
python                    2.7.15               h9bab390_4  
python-dateutil           2.7.5                    py27_0  
pytz                      2018.7                   py27_0  
pyzmq                     17.1.2           py27h14c3975_0  
qhull                     2015.2                        0    openalea
qt                        4.8.7                         2  
qtconsole                 4.4.2                    py27_0  
readline                  7.0                  h7b6447c_5  
scandir                   1.9.0            py27h14c3975_0  
scipy                     1.1.0            py27hd20e5f9_0  
send2trash                1.5.0                    py27_0  
setuptools                40.6.2                   py27_0  
simplegeneric             0.8.1                    py27_2  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.11.0                   py27_1  
sqlite                    3.25.3               h7b6447c_0  
terminado                 0.8.1                    py27_1  
testpath                  0.4.2                    py27_0  
tk                        8.6.8                hbc83047_0  
tornado                   5.1.1            py27h7b6447c_0  
traitlets                 4.3.2                    py27_0  
walter                    2.0.1                     <pip>
wcwidth                   0.1.7                    py27_0  
webencodings              0.5.1                    py27_1  
wheel                     0.32.3                   py27_0  
zeromq                    4.2.5                hf484d3e_1  
zlib                      1.2.11               h7b6447c_3

**Comment by pradal** [comment]
Interesting. The problem:
Due to the PATH variable, nosetests is found and will search some dependencies outside your conda environment.

To avoid this side effect, in your environnement, unset the LD_LIBRARY_PATh variable. 
Do you know where does it come from? Do you have it set in your .bashrc? Or in a Python config file?

**Comment by Emblanc** [comment]
It might be coming from my .bashrc. Here is what is written at the end of my .bashrc :

> # added by Miniconda2 installer

> export PATH="/home/walter/miniconda2/bin:$PATH"

**Comment by pradal** [comment]
It is OK. But who set the **LD_LIBRARY_PATH**?

**Comment by Emblanc** [comment]
I don't know

**Comment by Emblanc** [comment]
There is nothing about LD_LIBRARY_PATH in my .bashrc

**Comment by pradal** [comment]
Do you source .openalea?
Something like `source ~/.openalea.sh`
Have you a file ~/.pydistutils.cfg ?

**Comment by Emblanc** [comment]
I have a line to source openalea in my .bashrc, but it is commented :

> #source ~/.openalea.sh

I do not have a file ~/.pydistutils.cfg

**Comment by pradal** [comment]
OK. Can you test again by opening a new shell and just activate the walter environment.
If it works, I will close the issue.

**Comment by Emblanc** [comment]
It is working. Thank you very much for all your help !

**Comment by pradal** [comment]
You are welcome!
