### ISSUE TITLE
Problem with parallelization ?

### ISSUE THREAD

**Issue by Emblanc** [openalea-incubator/WALTer#59]
When running an important number of simulations, my computer is considerably slowed down, it often freezes and I can't use it.
Furthermore, some simulations do not work properly (I do not have all the output files at the end of the simulation but the simulation does not produce an error message) when I run an important number of simulations. But if I run the same simulation alone or with fewer simulations it works, which makes me think that my computer is overwhelmed when there is too many simulations (10 simulations is already too much).
I did not have this kind of problems when simulations were run one at a time.

**Comment by pradal** [comment]
Seems coherent. How many simulations are you running together?
I can investigate that later on.

**Comment by Emblanc** [comment]
Yesterday I ran 28 simulations and 11 of them did not work.
This morning, I ran 10 simulations (the ones that did not work yesterday). My computer froze until all simulations were done and one of them did not work.

**Comment by pradal** [comment]
This is mainly due to the fact that we launch more processes than your computer have. I may limit the number of simulations we run at the same time.

**Comment by Emblanc** [comment]
Great, I think this would solve the problem thank you !
