### ISSUE TITLE
Saving the simulation time

### ISSUE THREAD

**Issue by Emblanc** [openalea-incubator/WALTer#70]
It would be useful to save the information of the time that each simulation has run. For example, a file could be saved in each id-xx[...]xx output directory with the simulation time.

**Comment by pradal** [comment]
Who will have the responsability to save it? The project?

**Comment by Emblanc** [comment]
> Who will have the responsability to save it? The project?

Yes, I think this should be managed by the project

**Comment by Emblanc** [comment]
This issue was solved by PR #73
