### ISSUE TITLE
Invalid value warning 

### ISSUE THREAD

**Issue by Emblanc** [openalea-incubator/WALTer#77]
/home/walter/WALTer/src/walter_data/WALTer.lpy:2479: RuntimeWarning: invalid value encountered in double_scalars
  dico_PAR_per_axis[nump][numt][round(Tempcum, 1)] = row.Organ_PAR / Temperature / row.Organ_surface

**Comment by Emblanc** [comment]
nump =  11
numt =  (1, 2, 1)
round(Tempcum, 1) =  1284.3
row.Organ_PAR / Temperature / row.Organ_surface =  0.0 / 14.1818181818 / 0.0
/home/walter/WALTer/src/walter_data/WALTer.lpy:2479: RuntimeWarning: invalid value encountered in double_scalars
  dico_PAR_per_axis[nump][numt][round(Tempcum, 1)] = row.Organ_PAR / Temperature / row.Organ_surface
nump =  11
numt =  (1, 4)
round(Tempcum, 1) =  1284.3
row.Organ_PAR / Temperature / row.Organ_surface =  0.0 / 14.1818181818 / 0.0

**Comment by Emblanc** [comment]
Here is the parameter file for a simulation that produces the warning
[sim_scheme_invalid_value.csv.zip](https://github.com/openalea-incubator/WALTer/files/3085192/sim_scheme_invalid_value.csv.zip)

**Comment by Emblanc** [comment]
> What does it means?
> row.Organ_PAR / Temperature / row.Organ_surface = (row.Organ_PAR / Temperature) / row.Organ_surface = row.Organ_PAR / (Temperature * row.Organ_surface)
> 
> Is this what you want to express?

I simply copied and pasted the code "row.Organ_PAR / Temperature / row.Organ_surface" from WALTer.lpy.
Yes, it is equivalent to  "(row.Organ_PAR / Temperature) / row.Organ_surface" or "row.Organ_PAR / (Temperature * row.Organ_surface)"

**Comment by pradal** [comment]
So 0. / 0. raise an error. That's normal.

You can replace by:

dico_PAR_per_axis[nump][numt][round(Tempcum, 1)] = 0. if row.Organ_surface == 0. else row.Organ_PAR / (Temperature * row.Organ_surface)

**Comment by Emblanc** [comment]
Issue solved by PR #80
