### ISSUE TITLE
GAIprox is computed with the same neighbours for all plants

### ISSUE THREAD

**Issue by christian34** [openalea-incubator/WALTer#88]
The dummy variable used to iterate on neighbours of a plant for GAI prox computation is wrong: num_plante is used instead of num_plt, resulting in constant neighbouhood for all plants.  
Fixing this typo raise another error and will influence reference computation. I therefore open a new PR for solving this issue

` # Calcul du GAI de proximite`
`for num_plt in range(1,crop_scheme["nplant_peupl"] + 1):`
`    surface_peupl = 0`
` for num_voisin in dico_voisins[num_plante]:`

**Comment by christian34** [comment]
@Emblanc : for me the bug is fixed, but needs a change of reference simulation outputs: can you check / do this (after merging of PR #86 to ease reading) ?

**Comment by Emblanc** [comment]
This error is problematic for the results : it is a very good thing that you spotted it, thank you !

**Comment by christian34** [comment]
closed by PR #89
